project:
  type: website
  output-dir: docs
  
website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/smd-data/604-Assignment-5
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025"

format:
  html:
    theme: minty
    toc: true

editor: source

